---
title: "Adverse Drug Effects"
runtime: shiny
editor_options: 
  chunk_output_type: console
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: 
      version: 4
      bootswatch: simplex
---

```{r}
library(tidyverse)
library(ggrepel)
library(wordcloud2)
drugs <- read.csv("drugs.csv")
reports <- read.csv("reports.csv") |>
  mutate(
    death = ifelse(is.na(death), "Not dead", "Dead")
  )

```

<style>
.shiny-plot-output {
  border: solid black 2px;
  border-radius: 5px;
  overflow-x: hidden;
  overflow-y: hidden;
  margin-bottom: 5vh;
}

</style>

About
==========================

### Adverse Drug Effects
Cathal Mee, Daniel Evans


Row
---------------------------

### The Dataset
All of the data we used in this project was scraped from the FDA's public API; specifically, we used the adverse drug effects endpoint, which gives access to information about individual effect reports made by a variety of sources. In our initial collection of data, we separated each report into the various drugs that were included. Afterwards, we wrangled another dataset of reports, without individual drug information. After all this, we had access to the following variables.

```{r}
library(knitr)
fields <- data.frame(
  Name = c(
    "Date", "Reporter Qualifications", "Patient Onset Age", "Patient Sex",
    "Patient Weight", "Patient Reaction", "Reporter Qualification", "Country",
    "Drug Start Date", "Receive Date", "Time to Report", "Seriousness",
    "Death date", "Death"
  ),
  Type = c(
    "Numerical", "Categorical", "Numerical", "Categorical",
    "Numerical", "Text", "Categorical", "Categorical",
    "Date", "Date", "Numerical", "Categorical",
    "Date", "Boolean"
  ),
  Description = c(
    "The date that the report was submitted.",
    "What entity made a report on behalf of a patient.",
    "The age of the patient when the first effect occurred.",
    "The sex of the patient.",
    "The weight of the patient.",
    "Text data that includes all reactions experienced by the patient.",
    "The type of reporter; 1 = Physician, 2 = Pharmacist, 3 = Other health professional, 4 = Lawyer, 5 = Consumer or non-health professional.",
    "The name of the country where the event occurred.",
    "The date the patient began taking the drug.",
    "The date the report was received.",
    "To be calculated manually: the amount of time in between the drug start date and the date the report was received.",
    "Whether or not the report was considered serious.",
    "The date of death, if the patient died.",
    "Whether or not the patient died."
  )
)

kable(fields, format = "markdown", col.names = c("Name", "Type", "Description"))
```



### Objectives
Given the interactive nature of this dashboard, our aim is not to answer any single question about adverse drug effects in the United States; rather, we hope that these illustrations will allow for true exploration of trends in the data. There are four primary contexts to this data that we wanted users to be able to explore: reports, reporters, reactions, and locations. 

[Reports]

Given that the United States pharmaceutical industry is driven by capital, health care victims are often taken advantage of by big companies. These reports are one of the few ways that the producers of medications can be held accountable; thus, we thought it relevant to analyze the sources of these reports, to see how problems in the system are identified. Questions include what qualifications do the people making these reports have, whether or not sex or seriousness play a factor in how effects get reported, and how these trends may differ across time.

Of course, the foci of the data are the effects themselves. We wanted to observe the quantities of each effect, as well as how these reactions are distributed across demographics and seriousness. Since the effects are numerous, we also wanted to create a visualization that captures a big-picture view of the situation.

[Locations]

Reports
==========================
```{r}

```


Reporters
==========================

Inputs {.sidebar}
-------------------------
```{r, echo=FALSE}
inputPanel(
  div(
    selectInput("color", label = "Color By:", choices = c(
      "None" = "none",
      "Sex" = "sex",
      "Seriousness" = "seriousness",
      "Death" = "death"
    )),
    selectInput("limit", label = "Limit to:", choices = c(
      "No Limit" = "None",
      "Male" = "Male",
      "Female" = "Female",
      "Serious" = "Serious",
      "Deaths" = "Dead"
    )),
    sliderInput(
      "daterange", 
      label = "Dates:",
      min = as.Date("2015-01-01"), 
      max = as.Date("2020-01-01"), 
      value = c(as.Date("2015-01-01"), as.Date("2020-01-01")), 
      step = 1,
      timeFormat = "%Y-%m-%d"
    ),
    style = "display: flex; flex-direction: column;"
  )
)
```

Row
-------------------------------------
```{r}
renderPlot({
  req(input$color)
  
  filtered_reports <- reports |>
    filter(
      input$limit == sex | 
      input$limit == seriousness |
      input$limit == death |
      input$limit == "None"
    ) |>
    filter(
      as.Date(receive_date) >= input$daterange[1] &
      as.Date(receive_date) <= input$daterange[2]
    )
  
  if (input$color == "none") {
    labels <- filtered_reports |>
      filter(!is.na(qualification)) |>
      group_by(qualification) |>
      summarize(num = n()) |>
      mutate(prop = num/sum(num))
      
    labels |>
      mutate(qualification = fct_reorder(qualification, desc(prop))) |>
      arrange(desc(qualification)) |>
      mutate(cumprop = cumsum(prop)) |>
      ggplot() +
        geom_col(aes(x = "", y = prop, fill = qualification), width = 1, color = "black", size = .2) +
        geom_label(aes(x = 1.7, label = paste0(round(prop*100),"%"), y = cumprop - (prop/2)), size = 6) +
        coord_polar(theta = "y") +
        theme_void() +
        scale_fill_viridis_d(option="D") +
        labs(
          title = "Reporter Qualification Proportions",
          fill = "Qualification"
        )
  } else {
    filtered_reports |>
      filter(!is.na(qualification) & !is.na(.data[[input$color]])) |>
      group_by(qualification) |>
      mutate(n = n()) |>
      ungroup() |>
      mutate(
        qualification = fct_reorder(qualification, desc(n)),
        !!input$color := fct_relevel(.data[[input$color]], "Serious", "Male")
      ) |>
      ggplot(aes(x = qualification, fill = .data[[input$color]])) +
        geom_bar() +
        scale_fill_viridis_d(option = "C", end = .5) +
        labs(
          title = "Reporter Qualification Counts",
          x = "Qualification",
          y = "Count",
          fill = str_to_title(input$color)
        ) +
        theme_minimal()
  }
  
})
```


Reactions - Bar Chart
==========================

Page 1: Inputs {.sidebar}
-------------------------
```{r, include=FALSE}
reactions <- reports |>
    mutate(effects = str_split(effects, ";")) |>
    unnest(effects) |>
    rename(effect = effects) |>
    mutate(effect = str_to_upper(effect))

drugs200 <- drugs |> 
  mutate(drug = str_remove(drug, "\\.")) |>
  group_by(drug) |>
  summarize(n = n()) |>
  arrange(desc(n)) |>
  slice_head(n = 200)

drugnames <- str_to_upper(drugs200$drug)
  
```

```{r}
inputPanel(
  div(
    selectizeInput(
      "reactions", 
      "Add reactions:", 
      choices = sort(unique(reactions$effect)), 
      multiple = TRUE, 
      selected = c("IRRITABILITY","DEPRESSION","FATIGUE"),
      options = list(create = TRUE)
    ),
    selectInput("group", label = "Stratify By:", choices = c(
      "None" = "none",
      "Sex" = "sex",
      "Seriousness" = "seriousness",
      "Death" = "death"
    )),
    sliderInput(
      "agerange", 
      label = "Ages:",
      min = 0, 
      max = 120, 
      value = c(0, 120), 
      step = 1
    ),
    style = "display: flex; flex-direction: column;"
  )
)
```

Row
--------------------------
```{r}
renderPlot({
  req(input$reactions)
  req(input$group)
  
  if (input$group == "none") {
    reactions |>
      filter(
        effect %in% str_to_upper(input$reactions) &
        onset_age >= input$agerange[1] &
        onset_age <= input$agerange[2]
      ) |>
      group_by(effect) |>
      mutate(num = n()) |>
      ungroup() |>
      mutate(effect = fct_reorder(effect, num)) |>
      ggplot(aes(x = effect)) +
        geom_bar(fill = "black") +
        labs(
          title = "Drug Reactions",
          x = "Reactions",
          y = "Count"
        ) +
        theme_minimal()
  } else {
    reactions |>
      filter(
        effect %in% str_to_upper(input$reactions) &
        !is.na(.data[[input$group]]) &
        onset_age >= input$agerange[1] &
        onset_age <= input$agerange[2]
      ) |>
      group_by(effect, .data[[input$group]]) |>
      mutate(num = n()) |>
      ungroup() |>
      mutate(
        effect = fct_reorder(effect, num),
        !!input$group := fct_relevel(.data[[input$group]], "Serious", "Male")
      ) |>
      ggplot(aes(x = effect, fill = .data[[input$group]])) +
        geom_bar(position = "dodge") +
        scale_fill_viridis_d(option="F", end = .5) +
        labs(
          title = "Drug Reactions",
          x = "Reactions",
          y = "Count"
        ) +
        theme_minimal()
  }
})
```

Reactions - Wordcloud
==========================

Page 1: Inputs {.sidebar}
-------------------------
```{r}
inputPanel(
  selectizeInput(
      "drugs", 
      "Add drug:", 
      choices = sort(unique(drugnames)), 
      multiple = TRUE,
      options = list(create = TRUE)
  ),
  selectInput("wc_filter", label = "Limit to:", choices = c(
      "No Limit" = "None",
      "Male" = "Male",
      "Female" = "Female",
      "Serious" = "Serious",
      "Deaths" = "Dead"
    )),
  sliderInput(
      "wc_agerange", 
      label = "Ages:",
      min = 0, 
      max = 120, 
      value = c(0, 120), 
      step = 1
  )
)
```

Row
--------------------------
```{r}
renderWordcloud2({
  
  if (length(input$drugs)==0) {
    reactions |>
      filter(
        onset_age > input$wc_agerange[1] & 
        onset_age < input$wc_agerange[2] & 
        (input$wc_filter == sex | 
        input$wc_filter == seriousness |
        input$wc_filter == death |
        input$wc_filter == "None")
      ) |>
      group_by(effect) |>
      summarize(freq = n()) |>
      arrange(desc(freq)) |>
      slice_head(n = 200) |>
      wordcloud2(shape = "circle")
  } else {
    search <- str_c(input$drugs, collapse = "|")
    
    drugs |>
      # filter and unnest reactions
      filter(str_detect(drug, search)) |>
      mutate(effects = str_split(effects, ";")) |>
      unnest(effects) |>
      rename(effect = effects) |>
      mutate(effect = str_to_upper(effect)) |>
      # filter
      filter(
        onset_age > input$wc_agerange[1] & 
        onset_age < input$wc_agerange[2] & 
        (input$wc_filter == sex | 
        input$wc_filter == seriousness |
        input$wc_filter == death |
        input$wc_filter == "None")
      ) |>
      # wordcloud
      mutate(tot = n()) |>
      group_by(effect) |>
      summarize(freq = 10*n()/tot) |>
      arrange(desc(freq)) |>
      slice_head(n = 200) |>
      wordcloud2(shape = "circle")
  }
})
```
















